#!/usr/bin/env python3
"""Build the FLOPO flower sex-quality module (curator decision 2026-10-05).

FLOPO used to carry the general class axiom

    has_part some (owl:Thing and has_quality some 'phenotypic sex') SubClassOf owl:Nothing

which made every phenotype with a phenotypic-sex quality (PATO:0001894 and its children male,
female and hermaphrodite) unsatisfiable, so ``DeprecateDumbClasses.groovy`` obsoleted all of them.
The axiom is stricter than PATO itself: PATO defines phenotypic sex as an organismal quality, and
an organismal quality is "a quality that inheres in an entire organism or part of an organism"
(PATO:0001995).  Floras describe the sex of flowers all the time ("flowers bisexual", "male
flowers"), and the Plant Ontology has pistillate (PO:0025599) and staminate (PO:0025600) flowers.
The curator ruled that these phenotypes must be satisfiable.

``tools/update_flopo_sex_quality_release.py`` removes the axiom and embeds this module, which

* reinstates the four flower sex phenotypes that were obsoleted only because of the axiom, under
  their original identifiers (flower female, flower phenotypic sex, flower hermaphrodite, flower
  male), and
* adds the two phenotypes of the Saudi native-plants guide that the axiom blocked: pistillate
  flower female and staminate flower male (``config/flopo_sex_quality_id_registry.tsv``).

Obsolete sex phenotypes of other organs (anther male, awn phenotypic sex, ...) stay obsolete:
those combinations are mining artefacts, not botanical statements.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

from rdflib import DCTERMS, OWL, RDF, RDFS, XSD, BNode, Graph, Literal, Namespace, URIRef
from rdflib.collection import Collection

ROOT = Path(__file__).resolve().parents[1]
OBO = Namespace("http://purl.obolibrary.org/obo/")
MODULE = URIRef(OBO + "flopo-sex-quality-extension.owl")
REGISTRY = Path("config/flopo_sex_quality_id_registry.tsv")
OUTPUT = Path("ontology/flopo-sex-quality-extension.ttl")
DECISION_DATE = "2026-10-05"

HAS_PART = OBO.BFO_0000051
HAS_QUALITY = OBO.RO_0000053
DEFINITION = OBO.IAO_0000115
EDITOR_NOTE = OBO.IAO_0000116

REINSTATED_NOTE = (
    "Reinstated by curator decision {date}. The class was obsoleted only because FLOPO's general "
    "class axiom 'has_part some (owl:Thing and has_quality some phenotypic sex) SubClassOf "
    "owl:Nothing' made it unsatisfiable. PATO allows organismal qualities to inhere in a part of "
    "an organism (PATO:0001995), and floras state the sex of flowers, so the axiom was removed."
)
NEW_NOTE = (
    "Added by curator decision {date}: the NCVC Saudi native-plants guide states this phenotype, "
    "which the removed phenotypic-sex class axiom had made unsatisfiable."
)


def read_registry(root: Path = ROOT) -> list[dict[str, str]]:
    with (root / REGISTRY).open(encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle, delimiter="\t"))


def _eq(graph: Graph, cls: URIRef, entity: URIRef, quality: URIRef) -> None:
    has_quality = BNode()
    graph.add((has_quality, RDF.type, OWL.Restriction))
    graph.add((has_quality, OWL.onProperty, HAS_QUALITY))
    graph.add((has_quality, OWL.someValuesFrom, quality))
    intersection = BNode()
    graph.add((intersection, RDF.type, OWL.Class))
    members = BNode()
    Collection(graph, members, [entity, has_quality])
    graph.add((intersection, OWL.intersectionOf, members))
    has_part = BNode()
    graph.add((has_part, RDF.type, OWL.Restriction))
    graph.add((has_part, OWL.onProperty, HAS_PART))
    graph.add((has_part, OWL.someValuesFrom, intersection))
    graph.add((cls, OWL.equivalentClass, has_part))


def build(root: Path = ROOT) -> Graph:
    graph = Graph()
    graph.bind("obo", OBO)
    graph.bind("dcterms", DCTERMS)
    graph.add((MODULE, RDF.type, OWL.Ontology))
    graph.add((MODULE, RDFS.comment, Literal(__doc__.split("\n\n")[0], lang="en")))
    for row in read_registry(root):
        cls = OBO[row["flopo_id"].replace(":", "_")]
        entity = OBO[row["entity"]]
        quality = OBO[row["quality"]]
        graph.add((cls, RDF.type, OWL.Class))
        graph.add((cls, RDFS.label, Literal(row["label"], datatype=XSD.string)))
        graph.add((cls, DEFINITION, Literal(row["definition"], lang="en")))
        note = REINSTATED_NOTE if row["status"] == "reinstated" else NEW_NOTE
        graph.add((cls, EDITOR_NOTE, Literal(note.format(date=DECISION_DATE), lang="en")))
        graph.add((cls, DCTERMS.modified, Literal(DECISION_DATE, datatype=XSD.date)))
        _eq(graph, cls, entity, quality)
    return graph


def write(root: Path = ROOT) -> Path:
    graph = build(root)
    text = (
        "# FLOPO flower sex-quality module. Generated by tools/build_flopo_sex_quality_extension.py;\n"
        "# embedded in ontology/flopo.owl by tools/update_flopo_sex_quality_release.py.\n"
        + graph.serialize(format="turtle")
    )
    path = root / OUTPUT
    path.write_text(text, encoding="utf-8")
    return path


def main() -> None:
    argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter).parse_args()
    print(f"wrote {write()}")


if __name__ == "__main__":
    main()
